version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: shoeApp
    volumes:
      - ./shoeApp:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8050:80"
    volumes:
      - ./shoeApp:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
